### PR TITLE
Nvidia Display Driver optionals components

### PR DESCRIPTION
**Pull request by JGoutin**
Add optionals parameters for install following display related drivers : 
- 3DVision drivers: NV3DVision + NV3DVisionUSB.Driver
- HDMI audio driver: HDAudio

### CODE REVIEW

**Comment by Link-Satonaka** [comment]
Have you tested this? Looks fine to me, but you never know how the nvidia installer itself may behave.

FYI the reason I left out the HD Audio driver is because Windows Update will just get it for you- which means you can't NOT have it. Installing it here creates an entry in `installed programs`, which might mislead people into thinking it can be uninstalled.

Is there actually any value in installing the HD Audio driver here?

**Comment by JGoutin** [comment]
Yes, I tested this, and that work good.

Windows Update also install (sometime) driver for 3DVision when connected. But Nvidia drivers from Microsoft are not always up to date. Have possibility to install them directly from Nvidia make user sure that driver version is the last one.

**Comment by Link-Satonaka** [comment]
> This cost nothing to keep the HD audio driver as optional, users will install it (and use parameters in general) only if they need it.

I understand that, but I question how often this audio driver is updated. Note that this driver exclusively governs HDMI/DisplayPort audio. Would be silly to offer the option if all it does is reinstall the same version you already have every update.

**Comment by JGoutin** [comment]
Other possibles reasons for keep it : 

Installing Nvidia driver package uninstall all previously installed Nvidia Drivers. If user install audio driver manually and then use this chocolatey package to upgrade display driver, audio driver will be uninstalled (And eventually revert to Windows update ones). 

After looking on the web, I found some examples of problems of not-functioning or not-installed drivers with Windows update drivers versions (On Windows 10 main version upgrade by example). The solution was to install (up to date) drivers directly from Nvidia.

Audio driver update rate is one or two time by years (At least for the two previous versions).

Reinstalling the driver only increase a little the installation time, but drivers are downloaded even when not installed.


Personally, I don't use HDMI and don't install theses drivers, I add them because this was just 10s of work after the work for 3D Vision (I made this PR for this).

**Pull request merged**
